### ISSUE TITLE
Wild selector level idea

### ISSUE THREAD

**Issue by RomanFausek** [prantlf/storybook-multilevel-sort#2]
This saved so much time for me! 🚀

I was thinking that it would be nice for the wild selector to go to any level. Let's say I want `Playground` story first on any level.

Right now I have to do this:
```
'*': {
    playground: null,
    '*': {
      playground: null,
    },
  },
```
but once I introduce a new (deeper) level, this sorter won't work for it anymore

**Comment by prantlf** [comment]
I'm glad that you found this useful :-)

Yes, having a such selector would be useful. I'm thinking about having wild fallback selector, which would be used at the same or deeper level, if no explicit selector were provided for it. For example:

    '**': {
      playground: null,
    },

I'll need to test how it'd work.

**Comment by prantlf** [comment]
I added support for [nested wildcards](https://github.com/prantlf/storybook-multilevel-sort#nested-wildcards) in [1.2.0](https://github.com/prantlf/storybook-multilevel-sort/releases/tag/v1.2.0) as I sketched it [above](https://github.com/prantlf/storybook-multilevel-sort/issues/2#issuecomment-1328149700).

It allowed simplifying this sample configuration:

```js
const order = {
  articles: null,
  elements: {
    '*': { default: null },
  },
  components: {
    '*': { default: null },
  }
};
```

to this:

```js
const order = {
  articles: null,
  elements: null,
  components: null,
  '**': { default: null }
};
```

Will it work for you?

**Comment by RomanFausek** [comment]
@prantlf I didn't notice your messages, sorry. I didn't check the implementation yet but does it support more than two levels?

```
'*': {
    playground: null,
    '*': {
      playground: null,
      '*': {
        playground: null,
      },
    },
  },
```
